### ISSUE TITLE
grunt build error 

### ISSUE THREAD

**Issue by dongyado** [jwplayer/jwplayer#1504]
### Environment

- *pc*
- *ubuntu 14.04
- *jwplayer v7.7.2*
-  grunt
grunt-cli v0.1.13
grunt v1.0.1
- npm 
1.4.28

When I run grunt to build: 

`jwplayer v7.7.2+local.2016-10-24-12-18-43-600
Running "clean:dist" (clean) task
 2 paths cleaned.

Running "webpack" task
Fatal error: (release) jwplayer.js from UglifyJs
TypeError: Cannot read property '1' of null
  at Function.uglify.AST_Node.warn_function (/home/slayer/vhost/jwplayer/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:65:25)
  at Function.AST_Node.warn (<anonymous>:425:18)
  at Object.OutputStream.add_mapping (<anonymous>:4099:22)
  at options.defaults.sequences (<anonymous>:5190:16)
  at AST_Node.eval [as add_source_map] (<anonymous>:5151:13)
  at doit (<anonymous>:4188:18)
  at AST_Node.eval [as print] (<anonymous>:4195:13)
  at eval (<anonymous>:4936:22)
  at Array.forEach (native)
  at eval (<anonymous>:4930:29)
  at eval (<anonymous>:4056:19)
  at OutputStream.with_indent (<anonymous>:4030:38)
  at Object.with_block (<anonymous>:4055:9)
  at key (<anonymous>:4929:48)
  at doit (<anonymous>:4189:13)
  at AST_Node.eval [as print] (<anonymous>:4195:13)
  at parenthesize_for_noin (<anonymous>:4773:25)
  at expr (<anonymous>:4796:13)
  at doit (<anonymous>:4189:13)
  at AST_Node.eval [as print] (<anonymous>:4195:13)
  at eval (<anonymous>:4757:17)
  at Array.forEach (native)
  at AST_Node.noin [as _do_print] (<anonymous>:4755:26)
  at noin (<anonymous>:4766:14)
  at doit (<anonymous>:4189:13)
  at AST_Node.eval [as print] (<anonymous>:4195:13)
  at eval (<anonymous>:4448:22)
  at Array.forEach (native)
  at display_body (<anonymous>:4439:14)
  at eval (<anonymous>:4487:13)
  at eval (<anonymous>:4056:19)
  at OutputStream.with_indent (<anonymous>:4030:38)
  at Object.with_block (<anonymous>:4055:9)
  at print_bracketed (<anonymous>:4486:37)
  at AST_Node.b [as _do_print] (<anonymous>:4587:9)
  at b (<anonymous>:4590:14)
  at doit (<anonymous>:4189:13)
  at AST_Node.eval [as print] (<anonymous>:4195:13)
  at eval (<anonymous>:4918:21)
  at Array.forEach (native)
  at eval (<anonymous>:4916:15)
  at Object.with_square (<anonymous>:4075:19)
  at key (<anonymous>:4913:16)
  at doit (<anonymous>:4189:13)
  at AST_Node.eval [as print] (<anonymous>:4195:13)
  at eval (<anonymous>:4808:22)
  at Array.forEach (native)
  at eval (<anonymous>:4806:23)
  at Object.with_parens (<anonymous>:4067:19)
  at expr (<anonymous>:4805:16)
  at doit (<anonymous>:4189:13)
  at AST_Node.eval [as print] (<anonymous>:4195:13)
  at AST_Node.b [as _do_print] (<anonymous>:4598:24)
  at b (<anonymous>:4603:14)
  at doit (<anonymous>:4189:13)
  at AST_Node.eval [as print] (<anonymous>:4195:13)
  at eval (<anonymous>:4448:22)
  at Array.forEach (native)
  at display_body (<anonymous>:4439:14)
  at eval (<anonymous>:4487:13)
  at eval (<anonymous>:4056:19)
  at OutputStream.with_indent (<anonymous>:4030:38)
  at Object.with_block (<anonymous>:4055:9)
  at print_bracketed (<anonymous>:4486:37)
  at AST_Node.b [as _do_print] (<anonymous>:4587:9)
  at b (<anonymous>:4590:14)
  at doit (<anonymous>:4189:13)
  at AST_Node.eval [as print] (<anonymous>:4195:13)
  at eval (<anonymous>:4808:22)
  at Array.forEach (native)
  at eval (<anonymous>:4806:23)
  at Object.with_parens (<anonymous>:4067:19)
  at expr (<anonymous>:4805:16)
  at doit (<anonymous>:4189:13)
  at AST_Node.eval [as print] (<anonymous>:4195:13)
  at op (<anonymous>:4868:25)
  at doit (<anonymous>:4189:13)
  at AST_Node.eval [as print] (<anonymous>:4195:13)
  at AST_Lambda.DEFMETHOD.self (<anonymous>:4482:19)
  at doit (<anonymous>:4189:13)
  at AST_Node.eval [as print] (<anonymous>:4195:13)
  at eval (<anonymous>:4448:22)
  at Array.forEach (native)
  at display_body (<anonymous>:4439:14)
  at AST_Lambda.DEFMETHOD.self (<anonymous>:4473:9)
  at doit (<anonymous>:4189:13)
  at AST_Node.eval [as print] (<anonymous>:4195:13)
  at /home/slayer/vhost/jwplayer/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:112:10
  at Array.forEach (native)
  at Compilation.<anonymous> (/home/slayer/vhost/jwplayer/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:44:10)
  at Compilation.applyPluginsAsync (/home/slayer/vhost/jwplayer/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
  at Compilation.<anonymous> (/home/slayer/vhost/jwplayer/node_modules/webpack/lib/Compilation.js:567:9)
  at Compilation.applyPluginsAsync (/home/slayer/vhost/jwplayer/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Compilation.<anonymous> (/home/slayer/vhost/jwplayer/node_modules/webpack/lib/Compilation.js:563:8)
  at Compilation.applyPluginsAsync (/home/slayer/vhost/jwplayer/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Compilation.seal (/home/slayer/vhost/jwplayer/node_modules/webpack/lib/Compilation.js:525:7)
  at Compiler.<anonymous> (/home/slayer/vhost/jwplayer/node_modules/webpack/lib/Compiler.js:397:15)
  at /home/slayer/vhost/jwplayer/node_modules/webpack/node_modules/tapable/lib/Tapable.js:103:11
  at Compilation.<anonymous> (/home/slayer/vhost/jwplayer/node_modules/webpack/lib/Compilation.js:445:10)`

**Comment by johnBartos** [comment]
@dongyado I believe this is an issue with UglifyJS plugin for Webpack on Ubuntu. Try removing this line:

https://github.com/jwplayer/jwplayer/blob/master/webpack.config.js#L85

**Comment by dongyado** [comment]
Thanks, it's work for me when remove the line 85 of webpack.config.js.  And I found a another way to fix this.  Find the webpack in node_modules and edit its package.json, replace uglify-js 2.6.0 with 2.5.0, and remove the installed file of uglify-js in node_modules of webpack, and reinstall uglify-js, and when rebuild with grunt, there is no errors. Thanks for help me find the error is caused by uglify-js.

**Comment by dongyado** [comment]
replace uglify-js 2.6.0 with 2.5.0 fixed this without change webpack.config.js

**Comment by johnBartos** [comment]
@dongyado Great! If you want to contribute and make a PR with this change we'll merge it in. Otherwise, we'll tag this and get it changed when we can.
