### ISSUE TITLE
Error in "beforePlay" event handler: TypeError: Cannot read property 'pauseVideo' of null

### ISSUE THREAD

**Issue by yourchoice** [jwplayer/jwplayer#1529]
Hi, 

Just i saw this error when try to add play a video from youtube. 

Error in "beforePlay" event handler: TypeError: Cannot read property 'pauseVideo' of null
    at l.pause (http://ssl.p.jwpcdn.com/player/v/7.7.2/provider.youtube.js:1:3876)
    at u.init (http://content.jwplatform.com/libraries/OrzyLJtG.js?_=1478079262752:5:6628)
    at w (http://ssl.p.jwpcdn.com/player/v/7.7.2/vast.js:2:7012)
    at v (http://ssl.p.jwpcdn.com/player/v/7.7.2/vast.js:2:6840)
    at s (http://ssl.p.jwpcdn.com/player/v/7.7.2/vast.js:2:6415)
    at c.adcontroller.o (http://ssl.p.jwpcdn.com/player/v/7.7.2/vast.js:2:6129)
    at s (http://content.jwplatform.com/libraries/OrzyLJtG.js?_=1478079262752:1:10550)
    at d.triggerSafe (http://content.jwplatform.com/libraries/OrzyLJtG.js?_=1478079262752:1:9787)
    at w.trigger (http://content.jwplatform.com/libraries/OrzyLJtG.js?_=1478079262752:4:19775)
    at a (http://content.jwplatform.com/libraries/OrzyLJtG.js?_=1478079262752:1:10307)

And player seems to have a strange behavior when provider is youtube. Play pase working strange

**Comment by johnBartos** [comment]
We'll look into it when we can- the Youtube provider is being removed soon which makes this low priority

**Comment by robwalch** [comment]
We do not support use of ads plugin with the Youtube provider. Serving 3rd party ads over Youtube embeds violates Youtube's ToS.

You'll need to host video yourself or on your JW Player account if you want to use VAST advertising configs.
