### ISSUE TITLE
Exception Occuring while playing Sample Video

### ISSUE THREAD

**Issue by ravirajjak** [jwplayer/jwplayer#3294]
While running the sample Android JWplayer I am getting the following exceptions

java.lang.IllegalArgumentException: No enum constant com.longtailvideo.jwplayer.license.a.a.DEVELOPER
2019-02-15 19:07:38.141 27413-27840/com.jwplayer.opensourcedemo W/System.err:     at java.lang.Enum.valueOf(Enum.java:258)
2019-02-15 19:07:38.141 27413-27840/com.jwplayer.opensourcedemo W/System.err:     at com.longtailvideo.jwplayer.license.a.a.valueOf(SourceFile:9)
2019-02-15 19:07:38.142 27413-27840/com.jwplayer.opensourcedemo W/System.err:     at com.longtailvideo.jwplayer.core.a.b.storeKeyInformation(SourceFile:61)
2019-02-15 19:07:38.142 27413-27840/com.jwplayer.opensourcedemo W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2019-02-15 19:07:38.142 27413-27840/com.jwplayer.opensourcedemo W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:326)
2019-02-15 19:07:38.142 27413-27840/com.jwplayer.opensourcedemo W/System.err:     at android.os.Looper.loop(Looper.java:160)
2019-02-15 19:07:38.142 27413-27840/com.jwplayer.opensourcedemo W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by karimMourra** [comment]
Hi @ravirajjak, this space is for web player issues. For commercial products like the iOS and Android SDK please submit a support case at https://support.jwplayer.com/submit-support-case
