### ISSUE TITLE
Android app crashes when connecting a USB-C to HDMI adapter on Samsung Galaxy S8

### ISSUE THREAD

**Issue by bigfriedicecream** [jwplayer/jwplayer#3627]
### Expected Behavior

The app should not crash

### Actual Behavior

The app crashes

### Steps to reproduce

1. Open an application which contains a video implementation of JWPlayer (I have tested using this repo: https://github.com/jwplayer/jwplayer-sdk-android-demo)
2. Connect a USB-C to HDMI adapter to your phone
3. The app will crash

### Environment

- Samsung Galaxy s8
- Android version 8.0.0
- JWPlayer implementation "com.longtailvideo.jwplayer:jwplayer-core:3.6.0"

### Stack trace
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.media.action.HDMI_AUDIO_PLUG flg=0x40000010 (has extras) } in c.e.a.a.b.m$a@5cad2a2
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1656)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7770)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
	   
Caused by java.lang.NullPointerException: uriString
       at android.net.Uri$StringUri.<init>(Uri.java:496)
       at android.net.Uri$StringUri.<init>(Uri.java:486)
       at android.net.Uri.parse(Uri.java:458)
       at com.longtailvideo.jwplayer.player.c.a(c.java:17)
       at com.longtailvideo.jwplayer.player.c.onAudioCapabilitiesChanged(c.java:5)
       at com.google.android.exoplayer2.audio.AudioCapabilitiesReceiver$HdmiAudioPlugBroadcastReceiver.onReceive(AudioCapabilitiesReceiver.java:5)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1646)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7770)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

**Comment by robwalch** [comment]
Hi @bigfriedicecream,

This is the web player project. Issues with Android and iOS native SDKs should be [reported here](https://support.jwplayer.com/submit-support-case).
