### ISSUE TITLE
[Violation] Permissions policy violation: fullscreen is not allowed in this document.

### ISSUE THREAD

**Issue by princerb** [jwplayer/jwplayer#4043]
### Expected Behavior

*I want to watch a movie in <b>FULLSCREEN!</b>*

### Actual Behavior

*Video is NOT in fullscreen, so basically nothing happens when press F, or F11, or video's fullscreen option. I also tried to  open the video in Microsoft Edge, but still that error and video is not in fullscreen.*

### Steps to reproduce

1. Open a streamer website
2. Play a video
3. Then click on "Full screen" button from on right bottom video settings, or press F to get fullscreen mode.

### Environment

- Windows 11
- Chrome | 125.0.6422.61 (Official Build) (64-bit)
- JW Player  (version is possibly 8.32.1)

### Error messages:
```js
[Violation] Permissions policy violation: fullscreen is not allowed in this document.

Uncaught (in promise)                jwplayer.core.controls.js:10
TypeError: Disallowed by permissions policy
    at Object.requestFullscreen (jwplayer.core.controls.js:10:100522)
    at n.requestFullscreen (jwplayer.core.controls.js:10:101038)
    at Jt.ct (jwplayer.core.controls.js:10:119189)
    at i (jwplayer.js:9:43234)
    at Jt.trigger (jwplayer.js:9:44380)
    at Jt.<anonymous> (jwplayer.core.controls.js:10:129895)
    at i (jwplayer.js:9:43234)
    at T.trigger (jwplayer.js:9:44395)
    at T.set (jwplayer.js:9:24468)
    at te.mt (jwplayer.core.controls.js:10:145896)
```

### Screenshot:

![image](https://github.com/jwplayer/jwplayer/assets/77580222/80a72bff-99bb-42f2-9257-1359f1e9bd4e)

**Comment by andrewinsidelazarev** [comment]
Hi! Look here: [https://gist.github.com/andrewinsidelazarev/70f581460419813773aeb848f4ad8c62?permalink_comment_id=5279147#gistcomment-5279147](https://gist.github.com/andrewinsidelazarev/70f581460419813773aeb848f4ad8c62?permalink_comment_id=5279147#gistcomment-5279147)
